config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /ja|en/ do
    devise_for :users
    root "static_pages#home"
    resources :motels
    resources :rooms
    resources :equipments
    resources :reviews do
      resources :comments
    end
    resources :comments do
      resources :comments
    end
  end
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  has_many :hotel_equips
  has_many :motels, through: :hotel_equips

  validates :name, presence: true
  before_save :beatify

  private

  def beatify
    self.name = name.titleize
  end
end

app/controllers/equipments_controller.rb
class EquipmentsController < ApplicationController
  load_and_authorize_resource
  before_action :find_equipment, only: [:edit, :update, :destroy]

  def index
    @equipments = Equipment.page(params[:page])
                           .per Settings.per_page
  end

  def new
    @equipment = Equipment.new
  end

  def create
    @equipment = Equipment.new equipment_params

    if @equipment.save
      redirect_to equipments_path
    else
      render :new
    end
  end

  def show
  end

  def edit; end

  def update
    if @equipment.update_attributes equipment_params
      flash[:success] = t "flash.update_success"
      redirect_to equipments_path
    else
      render :edit
    end
  end

  def destroy
    @equipment.destroy
    flash[:success] = t "flash.delete_success"
    redirect_to equipments_path
  end

  private

  def find_equipment
    @equipment = Equipment.find_by params[:id]

    return if @equipment
    flash[:danger] = t "flash.no_equipment"
    redirect_to root_url
  end

  def equipment_params
    params.require(:equipment).permit :name
  end

end

app/views/equipments/_equipment.html.erb
<li>
  <%= link_to equipment.name, edit_equipment_path(equipment) %>
  <%= link_to t("delete"), equipment_path(equipment), method: :delete,
        data: {confirm: t("delete_confirm")}, class: "delete" %>
</li>

app/views/equipments/_form.html.erb
<%= form_for @equipment, url: yield(:url) do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="field">
  <%= f.label :name, class: "label" %>
  <%= f.text_field :name, class: "form-control input-add-new" %>
  </div>
  <div class="text-center">
    <%= f.submit yield(:button), class: "btn btn-custom2" %>
  </div>
<% end %>

app/views/equipments/edit.html.erb
<% provide :title, t("equipment.edit_equipment") %>
<% provide :button, t("edit") %>
<% provide :url, equipment_path(@equipment) %>
<h1><%= t "equipment.edit_equipment" %></h1>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= render "form" %>
  </div>
</div>

app/views/equipments/index.html.erb
<%= provide :title, t("equipment.title") %>
<%= link_to t("equipment.add_equipment"), new_equipment_path, class: "btn btn-custom3" %>
<div class="content">
  <ul id="equipments" class="equipments">
    <%= render partial:"equipment", collection: @equipments %>
  </ul>
</div>
<div id="paginator1">
  <%= paginate @equipments, remote: true %>
</div>

app/views/equipments/index.js.erb
$("#equipments").html("<%= j render partial:"equipment", collection: @equipments %>");
$("#paginator1").html("<%= j paginate(@equipments, remote: true) %>");

app/views/equipments/new.html.erb
<% provide :title, t("equipment.add_equipment") %>
<% provide :button, t("add") %>
<% provide :url, equipments_path %>
<h1><%= t "equipment.add_equipment" %></h1>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= render "form" %>
  </div>
</div>