config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /ja|en/ do
    devise_for :users
    root "static_pages#home"
    resources :motels
    resources :rooms
    resources :equipments
    resources :reviews do
      resources :comments
    end
    resources :comments do
      resources :comments
    end
  end
end

app/models/motel.rb
class Motel < ApplicationRecord
  has_many :hotel_rooms, inverse_of: :motel
  has_many :rooms, through: :hotel_rooms
  has_many :hotel_equips, inverse_of: :motel
  has_many :equipments, through: :hotel_equips
  has_many :reviews
  accepts_nested_attributes_for :hotel_equips, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :hotel_rooms, reject_if: :all_blank, allow_destroy: true

  mount_uploaders :images, ImagesUploader
  serialize :images, JSON
  validates :name, presence: true
  validates :address, presence: true,
    uniqueness: {case_sensitive: false}
  validates :phone, presence: true, :numericality => true,
    :length => { :minimum => 10, :maximum => 15 }
  validates :level, presence: true
  validate :validate_unique_equipment
  validate :validate_unique_room

  def validate_unique_equipment
    validate_uniqueness_of_in_memory(
      hotel_equips, [:motel_id, :equipment_id])
  end

  def validate_unique_room
    validate_uniqueness_of_in_memory(
      hotel_rooms, [:motel_id, :room_id])
  end
end

app/controllers/motels_controller.rb
class MotelsController < ApplicationController
  load_and_authorize_resource
  before_action :find_motel, only: [:edit, :update, :destroy]

  def index
    @motels = Motel.page(params[:page])
                   .per Settings.per_page
  end

  def new
    @motel = Motel.new
  end

  def create
    @motel = Motel.new motel_params

    if @motel.save
      redirect_to motels_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @motel.update_attributes motel_params
      flash[:success] = t "flash.update_success"
      redirect_to motels_path
    else
      render :edit
    end
  end

  def destroy
    @motel.destroy
    flash[:success] = t "flash.delete_success"
    redirect_to motels_path
  end

  private

  def motel_params
    params.require(:motel).permit :name, :description, :address, :phone, :level, {images: []},
      hotel_equips_attributes: [:id, :_destroy, :price, :equipment_id],
      hotel_rooms_attributes: [:id, :_destroy, :price, :room_id]
  end

  def find_motel
    @motel = Motel.find_by params[:id]

    return if @motel
    flash[:danger] = t "flash.no_motel"
    redirect_to root_url
  end
end

app/views/motels/_form.html.erb
<%= form_for @motel, url: yield(:url) do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="field">
  <%= f.label :name, class: "label" %>
  <%= f.text_field :name, class: "form-control input-add-new" %>
  </div>
  <div class="field">
  <%= f.label :description, class: "label" %>
  <%= f.text_field :description, class: "form-control input-add-new" %>
  </div>
  <div class="field">
  <%= f.label :address, class: "label" %>
  <%= f.text_field :address, class: "form-control input-add-new" %>
  </div>
  <div class="field">
  <%= f.label :phone, class: "label" %>
  <%= f.phone_field :phone, class: "form-control input-add-new" %>
  </div>
  <div class="field">
  <%= f.label :level, class: "label" %>
  <%= f.number_field :level, min: 0, max: 5, class: "form-control input-add-new" %>
  </div>
  <div class="field">
  <%= f.label :images, class: "label" %>
  <%= f.file_field :images, multiple: true, class: " input-add-new" %>
  </div>
  <h3 style="margin-left:180px;"><%= t "equipment.item" %></h3>
  <div id='equipments'>
    <%= f.fields_for :hotel_equips do |hotel_equip| %>
      <%= render 'hotel_equip_fields', :f => hotel_equip %>
    <% end %>
  </div>
  <div class='links' style="margin-left:180px;">
      <%= link_to_add_association t("equipment.add_equipment"), f, :hotel_equips %>
  </div>

  <h3 style="margin-left:180px;"><%= t "room.item" %></h3>
  <div id='rooms'>
    <%= f.fields_for :hotel_rooms do |hotel_room| %>
      <%= render 'hotel_room_fields', :f => hotel_room %>
    <% end %>
    <div class='links' style="margin-left:180px;">
      <%= link_to_add_association t("room.add_room"), f, :hotel_rooms %>
    </div>
  </div>
  <div class="text-center">
    <%= f.submit yield(:button), class: "btn btn-custom2" %>
  </div>
<% end %>

app/views/motels/_hotel_equip_fields.html.erb
 <div class='nested-fields'>
  <div class="field">
    <%= f.label :equipment_id, t("equipment.item"), class:"label" %>
    <%= f.collection_select :equipment_id, Equipment.all,
      :id, :name, {class: "form-control input-add-new"} %>
  </div>
  <div class="field">
    <%= f.label :price, t("price"), class:"label" %>
    <%= f.number_field :price, min: 0, value: 0, class: "form-control input-add-new" %>
  </div>
  <div style="margin-left:180px;">
  # <%= link_to_remove_association t("delete"), f %>
  </div>
</div>

app/views/motels/_hotel_room_fields.html.erb
 <div class='nested-fields'>
  <div class="field">
    <%= f.label :room_id, t("room.item"), class:"label"  %>
    <%= f.collection_select :room_id, Room.all,
      :id, :room_type, {class: "form-control input-add-new"} %>
  </div>
  <div class="field">
    <%= f.label :price, t("price"), class:"label"  %>
    <%= f.number_field :price, min: 0, value: 0, class: "form-control input-add-new" %>
  </div>
  <div style="margin-left:180px;">
  # <%= link_to_remove_association t("delete"), f %>
  </div>
</div>

app/views/motels/_motel.html.erb
<li>
  <%= link_to motel.name, edit_motel_path(motel) %>
  <%= link_to t("delete"), motel_path(motel), method: :delete,
        data: {confirm: t("delete_confirm")}, class: "delete" %>
</li>

app/views/motels/edit.html.erb
<% provide :title, t("hotel.edit_hotel") %>
<% provide :button, t("edit") %>
<% provide :url, motel_path(@motel) %>
<h1><%= t "hotel.edit_hotel" %></h1>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= render "form" %>
  </div>
</div>

app/views/motels/index.html.erb
<%= provide :title, t("hotel.title") %>
<%= link_to t("hotel.add_hotel"), new_motel_path, class: "btn btn-custom3" %>
<div class="content">
  <ul id="motels" class="motels">
    <%= render @motels %>
  </ul>
</div>
<div id="paginator1">
  <%= paginate @motels, remote: true %>
</div>

app/views/motels/index.js.erb
$("#motels").html("<%= j render(@motels) %>");
$("#paginator1").html("<%= j paginate(@motels, remote: true) %>");

app/views/motels/new.html.erb
<% provide :title, t("hotel.add_hotel") %>
<% provide :button, t("add") %>
<% provide :url, motels_path %>
<h1><%= t "hotel.add_hotel" %></h1>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= render "form" %>
  </div>
</div>