config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /ja|en/ do
    devise_for :users
    root "static_pages#home"
    resources :motels
    resources :rooms
    resources :equipments
    resources :reviews do
      resources :comments
    end
    resources :comments do
      resources :comments
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :hotel_rooms
  has_many :motels, through: :hotel_rooms

  validates :room_type, presence: true,
    uniqueness: {case_sensitive: false}
  validates :bed_numbers, presence: true
  validates :guest_no, presence: true
  before_save :beatify

  private

  def beatify
    self.room_type = room_type.titleize
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  load_and_authorize_resource
  before_action :find_room, only: [:edit, :update, :destroy]

  def index
    @rooms = Room.page(params[:page])
                 .per Settings.per_page
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new room_params

    if @room.save
      redirect_to rooms_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @room.update_attributes room_params
      flash[:success] = t "flash.update_success"
      redirect_to rooms_path
    else
      render :edit
    end
  end

  def destroy
    @room.destroy
    flash[:success] = t "flash.delete_success"
    redirect_to rooms_path
  end

  private

  def room_params
    params.require(:room).permit :room_type, :bed_numbers, :guest_no
  end

  def find_room
    @room = Room.find_by params[:id]

    return if @room
    flash[:danger] = t "flash.no_room"
    redirect_to root_url
  end

end

app/views/rooms/_form.html.erb
<%= form_for @room, url: yield(:url) do |f| %>
    <%= render "shared/error_messages", object: f.object %>
  <div class="field">
    <%= f.label :room_type, class: "label" %>
    <%= f.text_field :room_type, class: "form-control input-add-new" %>
  </div>
  <div class="field">
    <%= f.label :bed_numbers, class: "label" %>
    <%= f.number_field :bed_numbers, min: 1, class: "form-control input-add-new" %>
  </div>
  <div class="field">
    <%= f.label :guest_no, class: "label" %>
    <%= f.number_field :guest_no, min: 1, class: "form-control input-add-new" %>
  </div>
  <div class="text-center">
    <%= f.submit yield(:button), class: "btn btn-custom2" %>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<li>
  <%= link_to room.room_type, edit_room_path(room) %>
  <%= t("activerecord.attributes.room.bed_numbers") %>: <%= room.bed_numbers %>
  <%= t("activerecord.attributes.room.guest_no") %>: <%= room.guest_no %>
  <%= link_to t("delete"), room_path(room), method: :delete,
        data: {confirm: t("delete_confirm")}, class: "delete" %>
</li>

app/views/rooms/edit.html.erb
<% provide :title, t("room.edit_room") %>
<% provide :button, t("edit") %>
<% provide :url, room_path(@room) %>
<h1><%= t "room.edit_room" %></h1>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= render "form" %>
  </div>
</div>

app/views/rooms/index.html.erb
<%= provide :title, t("room.title") %>
<%= link_to t("room.add_room"), new_room_path, class: "btn btn-custom3" %>
<div class="content">
  <ul id="rooms" class="rooms">
    <%= render @rooms %>
  </ul>
</div>
<div id="paginator1">
  <%= paginate @rooms, remote: true %>
</div>

app/views/rooms/index.js.erb
$("#rooms").html("<%= j render(@rooms) %>");
$("#paginator1").html("<%= j paginate(@rooms, remote: true) %>");

app/views/rooms/new.html.erb
<% provide :title, t("room.add_room") %>
<% provide :button, t("add") %>
<% provide :url, rooms_path %>
<h1><%= t "room.add_room" %></h1>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= render "form" %>
  </div>
</div>